export const WEATHER_DESC_MAP = {
  'Clear sky': 'Quang đãng',
  'Mainly clear': 'Hầu hết quang đãng',
  'Partly cloudy': 'Ít mây',
  'Overcast': 'U ám',
  'Foggy': 'Sương mù',
  'Depositing rime fog': 'Sương mù đóng băng',
  'Light drizzle': 'Mưa phùn nhẹ',
  'Moderate drizzle': 'Mưa phùn',
  'Dense drizzle': 'Mưa phùn dày',
  'Slight rain': 'Mưa nhẹ',
  'Moderate rain': 'Mưa vừa',
  'Heavy rain': 'Mưa to',
  'Snow grains': 'Tuyết nhỏ',
  'Slight snow': 'Tuyết nhẹ',
  'Moderate snow': 'Tuyết vừa',
  'Heavy snow': 'Tuyết dày',
  'Slight rain showers': 'Mưa rào nhẹ',
  'Moderate rain showers': 'Mưa rào',
  'Violent rain showers': 'Mưa rào to',
  'Slight snow showers': 'Tuyết rơi nhẹ',
  'Heavy snow showers': 'Tuyết rơi dày',
  'Thunderstorm': 'Mưa dông',
  'Thunderstorm with slight hail': 'Mưa dông có mưa đá',
  'Thunderstorm with heavy hail': 'Mưa dông mưa đá to',
  'Sunny': 'Nắng',
  'Partly Clear': 'Ít mây',
  'Mostly Clear': 'Hầu hết quang đãng',
  'Clear': 'Quang đãng',
  'Cloudy': 'Nhiều mây',
  'Mostly Cloudy': 'Nhiều mây',
  'Showers': 'Mưa rào',
  'Thundershowers': 'Mưa dông',
  'Rain': 'Mưa',
  'With Fog': 'Sương mù',
  'Fog': 'Sương mù',
  'Scattered Showers': 'Mưa rải rác',
  'Light Rain': 'Mưa nhẹ',
  'Snow': 'Tuyết',
  'Windy': 'Có gió',
  'Quang đãng': 'Quang đãng',
  'Hầu hết quang đãng': 'Hầu hết quang đãng',
  'Ít mây': 'Ít mây',
  'U ám': 'U ám',
  'Sương mù': 'Sương mù',
  'Mưa phùn nhẹ': 'Mưa phùn nhẹ',
  'Mưa phùn': 'Mưa phùn',
  'Mưa nhẹ': 'Mưa nhẹ',
  'Mưa vừa': 'Mưa vừa',
  'Mưa to': 'Mưa to',
  'Mưa rào': 'Mưa rào',
  'Mưa dông': 'Mưa dông',
  'Nắng': 'Nắng',
  'Nhiều mây': 'Nhiều mây',
  'Tuyết': 'Tuyết',
  'Có gió': 'Có gió',
  'Nắng đẹp': 'Nắng đẹp',
  'Mưa nặng': 'Mưa nặng',
  'Có sương mù': 'Có sương mù',
};

export const DAY_NAMES = ['Chủ Nhật', 'Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Bảy'];

